# Generated by Django 5.0.2 on 2024-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_member_age'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['fname', 'email'], name='database_me_fname_ee15aa_idx'),
        ),
    ]
